services:
  - type: web
    name: my-streamlit-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run web_code.py --server.port $PORT --server.address 0.0.0.0"
